### ISSUE TITLE
How to use the opencv 4

### ISSUE THREAD

**Issue by YANG-ERA** [Schadenfreude-star/OpenGLStudy#1]
Hello, Mimple,! I want to use your code for my project. Could you please give me your code? plz

**Comment by Schadenfreude-star** [comment]
This is an OpenGL repo, not an OpenCV one. The source code is in History and you can render different object with it. The project is run on Windows. If you have Visual Studio, open the `opengl.sln` file and build. If you want executive file, please contact me.

**Comment by YANG-ERA** [comment]
6
